# Generated by Django 4.0.6 on 2022-12-22 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Main_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('certificate', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='courses.certificate')),
                ('institution', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='courses.institute')),
                ('language', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='courses.language')),
                ('main_subject', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='courses.main_subject')),
                ('provider', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='courses.provider')),
                ('sub_subject', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='courses.sub_subject')),
                ('university', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='courses.university')),
            ],
        ),
    ]
