# Generated by Django 4.0.6 on 2022-12-22 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_subject',
            name='main_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.main_subject'),
        ),
    ]
