# Generated by Django 4.0.6 on 2022-12-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='institute',
            name='img',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='provider',
            name='img',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='university',
            name='img',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
