# Generated by Django 4.0.6 on 2022-12-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_author_course_sub_title_institute_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_subject',
            name='img',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
