# Generated by Django 4.0.6 on 2022-12-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_author_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='description',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='institute',
            name='img',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='provider',
            name='img',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='sub_subject',
            name='description',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='university',
            name='img',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
